"use client";
import { useState } from "react";
export function InquiryForm({available}:{available:boolean}) {
 const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [draft,setDraft]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("");const data=new FormData(e.currentTarget);const firstName=String(data.get("name")||"");const email=String(data.get("email")||"");const subject=String(data.get("topic")||"");const message=String(data.get("message")||"");
 if(!available){const body=`Name: ${firstName}\nReply email: ${email}\n\n${message}`;setDraft(`mailto:info@miseth.org?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);setStatus("Your draft is ready. Open it in your email app, review it, and press Send there. Nothing has been sent from this website.");return;}
 setBusy(true);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName,email,subject,message,consent:true})});if(!response.ok)throw Error();setStatus("Your inquiry has been saved for the MIS team.");}catch{setStatus("We could not submit your inquiry. Please email info@miseth.org; your text remains in the form.");}finally{setBusy(false);}}
 return <form onSubmit={submit} className="space-y-5"><p className="leading-7 text-slate-600">{available?"Send a general inquiry to MIS.":"Prepare an inquiry below, then send it through your email app. This website does not send email directly."}</p><label className="block font-semibold">Your name<input name="name" autoComplete="name" required maxLength={80} className="mt-2 block w-full rounded-lg border p-3"/></label><label className="block font-semibold">Email<input name="email" type="email" autoComplete="email" required maxLength={200} className="mt-2 block w-full rounded-lg border p-3"/></label><label className="block font-semibold">Inquiry topic<select name="topic" className="mt-2 block w-full rounded-lg border bg-white p-3">{['General inquiry','Partnership','Child sponsorship','Donation inquiry','Volunteering','In-kind support','Document request'].map(t=><option key={t}>{t}</option>)}</select></label><label className="block font-semibold">Message<textarea name="message" required maxLength={3000} rows={5} className="mt-2 block w-full rounded-lg border p-3"/></label><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" required className="mt-1"/>I have read the privacy notice and agree to share these details with MIS for this inquiry.</label><p className="text-sm leading-6 text-slate-600">Please avoid sensitive personal or child-protection case details. <a href="/privacy" className="underline">Privacy notice</a></p><button disabled={busy} className="rounded-lg bg-navy px-6 py-3 font-semibold text-white disabled:opacity-50">{busy?"Submitting…":available?"Submit inquiry":"Prepare email draft"}</button><p role="status" className="leading-7">{status}</p>{draft?<a href={draft} className="text-link">Open email draft →</a>:null}</form>;
}
