"use client";
import { ProjectPhoto } from "@/components/sections/project-photo";
import { getProjectMedia } from "@/data/project-media";
import { useState } from "react";
import Link from "next/link";
export type NewsEntry = {title: string; description: string; href: string; category: string; location: string; period: string};
export function NewsExplorer({entries}: {entries: NewsEntry[]}) {
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("");
 const visible=entries.filter(e=>(!category || e.category===category) && `${e.title} ${e.description} ${e.location} ${e.period}`.toLowerCase().includes(query.trim().toLowerCase()));
 return <><div className="grid gap-4 rounded-2xl bg-slate-100 p-6 md:grid-cols-[2fr_1fr]"><label className="text-sm font-semibold text-navy">Search updates<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Keyword or location" className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal"/></label><label className="text-sm font-semibold text-navy">Topic<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal"><option value="">All topics</option>{[...new Set(entries.map(e=>e.category))].map(c=><option key={c}>{c}</option>)}</select></label></div><p role="status" className="my-6 text-sm text-slate-600">{visible.length} updates shown</p><div className="grid gap-6 md:grid-cols-2">{visible.map(e=><article key={e.href} className="group rounded-2xl border border-slate-200 p-7"><ProjectPhoto media={getProjectMedia(e.href.split("/").pop() || "")} className="-mx-7 -mt-7 mb-6 rounded-t-2xl" sizes="(max-width: 768px) 100vw, 50vw"/><p className="eyebrow">{e.category}</p><h2 className="mt-4 text-2xl font-semibold text-navy"><Link href={e.href}>{e.title}</Link></h2><p className="mt-3 text-sm text-slate-500">{e.period}{e.location ? ` · ${e.location}` : ""}</p><p className="mt-4 leading-7 text-slate-600">{e.description}</p><Link href={e.href} className="text-link mt-5">Read more →</Link></article>)}</div>{!visible.length && <p className="py-8 text-slate-600">No updates match your search.</p>}{(query || category) && <button className="text-link mt-6" onClick={()=>{setQuery("");setCategory("");}}>Clear filters</button>}</>;
}
