import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, ShieldCheck, Users, Handshake, Heart, BookOpen, Sprout, Target, Eye, CheckCircle2, HelpingHand } from "lucide-react";
import { ProjectPhoto } from "@/components/sections/project-photo";
import { ProjectGallery } from "@/components/sections/project-gallery";
import { CmsUpdates } from "@/components/sections/cms-updates";
import { ProjectCard } from "@/components/sections/project-card";
import { mediaLibrary } from "@/data/project-media";
import { projects } from "@/data/projects";
import { siteConfig } from "@/data/constants";
export const revalidate = 60;
function Action({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <Link href={href} className={`giving-button ${light?'giving-button-light':''}`}>{children}<span><ArrowUpRight size={22}/></span></Link>;}
const services=[{icon:ShieldCheck,title:"Protection for children",body:"Safe spaces, family support and community systems that put children’s well-being first.",href:"/programs#child-protection"},{icon:BookOpen,title:"Opportunity through education",body:"School follow-up, learning materials and summer programs that help children keep learning.",href:"/programs#education"},{icon:Sprout,title:"Nutrition and family resilience",body:"Connecting meals, essential support and livelihoods with stronger family well-being.",href:"/programs#nutrition"}];
export default function Home(){return <>
<section className="giving-hero">
 <Image src={mediaLibrary.community.src} alt="Temporary stock photograph for MIS’s homepage" fill preload sizes="100vw" className="giving-hero-image"/>
 <div className="giving-hero-shade"/>
 <div className="site-wrap giving-hero-main"><div className="hero-copy giving-hero-content"><p className="giving-kicker giving-kicker-light">Support. Empower. Transform.</p><h1>Stronger communities.<br/>Brighter futures.<br/><span>Together.</span></h1><p className="giving-hero-description">Working alongside children, women and underserved communities in Ethiopia to build protection, opportunity and lasting change.</p><div className="giving-hero-actions"><Action href="/donate">Support our work</Action><Link href="/projects" className="giving-story-link"><span><ArrowUpRight size={23}/></span>Explore our impact</Link></div></div></div>
 <div className="site-wrap giving-hero-promises">{[{title:"Locally led action",body:"Working through local structures and community participation."},{title:"Integrated support",body:"Connecting education, protection, health and family resilience."},{title:"Documented experience",body:"Current work and past projects, with clearly reported results."}].map(p=><div key={p.title}><h2><CheckCircle2 size={20}/>{p.title}</h2><p>{p.body}</p></div>)}</div>
 <p className="giving-photo-label">Temporary stock photo · MIS imagery coming soon</p>
</section>
<section className="site-section giving-soft"><div className="site-wrap giving-about-grid"><div className="giving-collage"><ProjectPhoto media={mediaLibrary.support} className="giving-collage-main" sizes="(max-width: 900px) 90vw, 42vw"/><ProjectPhoto media={mediaLibrary.education} className="giving-collage-small" sizes="(max-width: 900px) 45vw, 22vw"/><div className="giving-collage-note"><Heart size={24}/><span>Rooted in communities.<br/><strong>Driven by care.</strong></span></div></div><div><p className="giving-kicker">About MIS Ethiopia</p><h2 className="section-title">Bringing people together.<br/><span className="giving-muted">Creating lasting change.</span></h2><p className="giving-body">Multi Integrated Support is an Ethiopian national civil society organization. We connect immediate assistance with long-term development for disadvantaged mothers, children and hard-to-reach communities.</p><div className="giving-purpose-grid"><article><span className="giving-icon"><Target/></span><h3>Our mission</h3><p>Improve access to health and education, support income generation and care for the environment through community participation.</p></article><article className="giving-red-card"><span className="giving-icon"><Eye/></span><h3>Our vision</h3><p>Poor, disadvantaged and hard-to-reach communities living in safe and decent conditions.</p></article></div><Action href="/about">Get to know MIS</Action></div></div></section>
<section className="site-section giving-services"><div className="site-wrap"><div className="giving-center"><p className="giving-kicker">Our programs</p><h2 className="section-title">Connected support.<br/>For every stage of life.</h2></div><div className="giving-service-grid">{services.map(s=><article key={s.title} className="giving-service-card"><span className="giving-icon"><s.icon/></span><h3>{s.title}</h3><p>{s.body}</p><Link href={s.href} className="giving-card-link">Explore program <ArrowUpRight size={22}/></Link></article>)}</div><p className="giving-section-note">Eight complementary areas. One community-centered approach. <Link href="/programs">Explore all programs <ArrowUpRight size={16}/></Link></p></div></section>
<section className="site-section giving-dark"><div className="site-wrap giving-feature-grid"><div><p className="giving-kicker giving-kicker-light">Why our approach matters</p><h2 className="section-title">Local understanding.<br/><span className="giving-muted-light">Support that connects.</span></h2><p className="giving-body">People’s needs do not exist in isolation. MIS works with communities and partners to build practical responses around their priorities.</p><div className="giving-feature-list">{[{icon:Users,title:"Communities shape the response",body:"Participation helps identify priorities and develop locally relevant activities."},{icon:Handshake,title:"Partnership strengthens delivery",body:"We coordinate with local government, community structures and program partners."},{icon:ShieldCheck,title:"Dignity guides our work",body:"Safeguarding, inclusion and responsible reporting inform our approach."}].map(x=><div key={x.title}><span className="giving-icon"><x.icon/></span><div><h3>{x.title}</h3><p>{x.body}</p></div></div>)}</div><Action href="/partners">Partner with MIS</Action></div><div className="giving-feature-photo"><ProjectPhoto media={mediaLibrary.community} className="h-full" sizes="(max-width: 900px) 100vw, 45vw"/><div className="giving-feature-stat"><strong>229</strong><span>children in our active initiative<br/>August 2026 caseload</span></div></div></div></section>
<section className="site-section"><div className="site-wrap"><div className="giving-section-heading"><div><p className="giving-kicker">Our initiatives</p><h2 className="section-title">Practical action.<br/><span className="giving-muted">Meaningful support.</span></h2></div><Action href="/projects">Explore all projects</Action></div><div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{[projects[0],projects[5],projects[1]].map(p=><ProjectCard key={p.slug} project={p}/>)}</div></div></section>
<section className="site-section giving-soft"><div className="site-wrap"><div className="giving-center"><p className="giving-kicker">Our documented experience</p><h2 className="section-title">The people behind<br/>our project numbers.</h2></div><div className="giving-stat-grid">{[projects[1],projects[3],projects[2],projects[0]].map(p=><Link key={p.slug} href={`/projects/${p.slug}`}><strong>{p.figure}</strong><h3>{p.unit}</h3><p>{p.qualifier}</p></Link>)}</div><p className="giving-section-note">Different projects and reporting periods. Figures represent distinct measures and are not a combined total.</p></div></section>
<ProjectGallery/>
<section className="site-section"><div className="site-wrap giving-involve-grid"><div><p className="giving-kicker">Be part of the next chapter</p><h2 className="section-title">Your involvement<br/><span className="giving-muted">can make a difference.</span></h2><p className="giving-body">Whether you represent an organization, want to share your skills or are ready to support a program, there is a conversation worth starting.</p><Action href="/donate">Find your way to help</Action></div><div className="giving-involve-options">{[["01","Support children and families","Explore education, nutrition and child-centered support.","/sponsorship"],["02","Build a partnership","Bring funding, expertise or joint program opportunities.","/partners"],["03","Share skills and resources","Discuss volunteering or an in-kind contribution.","/donate"]].map(([n,t,d,h])=><Link href={h} key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight/></Link>)}</div></div></section>
<section className="site-section giving-soft"><div className="site-wrap giving-faq-grid"><aside className="giving-faq-contact"><HelpingHand size={42}/><h2>Let’s connect &amp;<br/>make a difference.</h2><p>Have questions about MIS or our work? Our team can help you find the right information.</p><Action href="/contact" light>Contact our team</Action></aside><div><p className="giving-kicker">Your questions answered</p><h2 className="section-title">A little more about<br/>working with MIS.</h2><div className="giving-faq">{[["Where does MIS work?","Our active child-protection initiative operates in Kolfe Keranyo, Addis Ababa. Our broader experience includes Addis Ababa, Amhara, Benishangul-Gumuz and Oromia. The project portfolio distinguishes active work from past experience."],["How can I support a program?","Contact MIS to discuss current priorities, sponsorship, partnership or in-kind support. Our team will explain giving and receipt arrangements. Online payments are not currently active."],["Can I read reports and organizational documents?","Our Resources page includes downloadable public briefs. Annual reports, financial information and full organizational policies can be requested directly from MIS."],["How does MIS protect children’s privacy?","We aim to protect dignity and confidentiality in public communication. Please contact the office for the appropriate confidential reporting route and avoid sharing identifying case details through general inquiries."]].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></div></section>
<section className="site-section"><div className="site-wrap"><div className="giving-section-heading"><div><p className="giving-kicker">Stories from our work</p><h2 className="section-title">Learning, participation<br/><span className="giving-muted">and community action.</span></h2></div><Action href="/news">All updates</Action></div><div className="grid gap-7 md:grid-cols-2">{[projects[5],projects[0]].map(p=><article className="giving-news-card group" key={p.slug}><ProjectPhoto media={p.slug==='kolfe-summer-school'?mediaLibrary.education:mediaLibrary.community} className="rounded-2xl" sizes="(max-width:768px) 100vw, 50vw"/><p>{p.slug==='kolfe-summer-school'?'2026 summer program':'Program overview · August 2026'}</p><h3><Link href={`/projects/${p.slug}`}>{p.title}<ArrowUpRight size={24}/></Link></h3></article>)}</div></div></section><CmsUpdates/>
<section className="giving-final"><div className="site-wrap"><Heart size={44}/><h2>Small acts of support.<br/>A stronger future, together.</h2><Action href={`mailto:${siteConfig.email}`} light>Start a conversation</Action></div></section>
</>;}
