"use server";
import { timingSafeEqual } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { clearAdminSession, createAdminSession, requireAdmin } from "@/lib/auth";
import { hasDatabase, prisma } from "@/lib/prisma";
const val=(f:FormData,k:string)=>String(f.get(k)??"").trim();
const safe=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
const slugify=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const status=(s:string)=>s==="DRAFT"?"DRAFT" as const:s==="HIDDEN"?"HIDDEN" as const:"PUBLISHED" as const;
export async function loginAction(f:FormData){const e=val(f,"email").toLowerCase(),p=val(f,"password"),ee=process.env.ADMIN_EMAIL?.toLowerCase()??"",ep=process.env.ADMIN_PASSWORD??"";if(!ee||!ep||!safe(e,ee)||!safe(p,ep))redirect("/admin/login?error=1");await createAdminSession(e);redirect("/admin");}
export async function logoutAction(){await clearAdminSession();redirect("/admin/login");}
export async function saveProgramAction(f:FormData){await requireAdmin();if(!hasDatabase())throw new Error("Database not configured");const id=val(f,"id"),title=val(f,"title"),slug=slugify(val(f,"slug")||title);const data={title,slug,shortDescription:val(f,"shortDescription"),fullDescription:val(f,"fullDescription")||null,category:val(f,"category")||null,featuredImage:val(f,"featuredImage")||null,buttonText:val(f,"buttonText")||"Learn More",buttonLink:val(f,"buttonLink")||null,displayOrder:Number(val(f,"displayOrder"))||0,showOnHomepage:f.get("showOnHomepage")==="on",status:status(val(f,"status"))};if(id)await prisma.program.update({where:{id},data});else await prisma.program.create({data});revalidatePath("/");revalidatePath("/programs");redirect("/admin?tab=programs");}
export async function saveProjectAction(f:FormData){await requireAdmin();if(!hasDatabase())throw new Error("Database not configured");const id=val(f,"id"),title=val(f,"title"),slug=slugify(val(f,"slug")||title);const data={label:val(f,"label")||null,title,slug,description:val(f,"description"),location:val(f,"location")||null,image:val(f,"image")||null,buttonText:val(f,"buttonText")||"Learn More",buttonLink:val(f,"buttonLink")||null,featured:f.get("featured")==="on",displayOrder:Number(val(f,"displayOrder"))||0,status:status(val(f,"status"))};if(id)await prisma.project.update({where:{id},data});else await prisma.project.create({data});revalidatePath("/");revalidatePath("/news");revalidatePath("/content/project/[slug]","page");redirect("/admin?tab=projects");}
export async function saveSettingAction(f:FormData){await requireAdmin();if(!hasDatabase())throw new Error("Database not configured");const key=val(f,"key"),raw=val(f,"value");let parsed:unknown;try{parsed=JSON.parse(raw)}catch{throw new Error("Setting must be valid JSON")}await prisma.siteSetting.upsert({where:{key},update:{value:parsed as object},create:{key,value:parsed as object}});revalidatePath("/");redirect("/admin?tab=settings");}